baseURL = "https://brujordet.no/"
languageCode = "en-us"
title = "Anders Brujordet"
theme = "hermit"
[params]
  description = "These are not the pages you are looking for"
  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/brujoand"
  [[params.social]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/brujoand"
  [[params.social]]
    name = "github"
    url = "https://www.github.com/brujoand"
